export PYTHONPATH="/workspace/laiminxin/vla-opt/third_party/CogVLA:/workspace/laiminxin/vla-opt:${PYTHONPATH}"
CUDA_VISIBLE_DEVICES=6 torchrun --standalone --nnodes 1 --nproc-per-node 1 vla-scripts/finetune.py \
  --vla_path openvla/openvla-7b \
  --data_root_dir /workspace/laiminxin/datasets/libero_rlds \
  --dataset_name libero_4_task_suites_no_noops \
  --run_root_dir /workspace/laiminxin/vla-opt/third_party/CogVLA/runs/cogvla-libero \
  --use_l1_regression True \
  --use_diffusion False \
  --use_film True \
  --use_aggr True \
  --num_vision_aggr 64 \
  --use_lfp True \
  --lfp_average_factor 0.5 \
  --lfp_type 'shiftedcos_decay_0.85_0.15' \
  --lfp_enable_film True \
  --num_images_in_input 2 \
  --use_proprio True \
  --batch_size 16 \
  --grad_accumulation_steps 1 \
  --learning_rate 5e-4 \
  --max_steps 80005 \
  --save_freq 10000 \
  --merge_lora_during_training False \
  --save_latest_checkpoint_only False \
  --image_aug True \
  --lora_rank 32 \
  --wandb_entity "mxlai1224-ustc" \
  --wandb_project "cogvla-libero" \
  --run_id_note cogvla-libero-4task \
  --monitor_log_interval 500 \
  --lfp_monitor_interval 500 \
  --wandb_log_freq 500